version: "3.6"
networks:
  main:
  db:
services:
  # admin:
  #   image: 
  #   ports:
  #    - ${ADMIN_PORT}:80
  #   networks:
  #     - main

  # client:
  #   image: 
  #   restart: unless-stopped
  #   networks:
  #     - main

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${APP_PORT}:80
    depends_on:
      - php
      - client
    networks:
      - main
